# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db366c462b19a50d61dc84333169f3fe45d29fcafa367420c6d8ff36854a43a84176d1b8a08e37f6ea46fdd79ac125aff5070d8f3121d66fac33d5323e8cf133

test:
  secret_key_base: 9268d2f6bdd05c8ca1830b2e3f224207ca30fdf36f4c51f480eceeb3f7818214b56ec92e9a193dd7961e11cd36b89fc8e23d3354517875593e3bffbae7a4f1c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
